# Generated by Django 5.0.7 on 2024-07-31 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('br_app', '0002_tasks_delete_bretech'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
