# Generated by Django 5.0.7 on 2024-07-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br_app', '0003_rename_tasks_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
